# Generated by Django 3.0.3 on 2021-11-11 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('microscopy', models.CharField(max_length=200)),
                ('cell_type', models.CharField(max_length=200)),
                ('component', models.CharField(max_length=200)),
                ('organism', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('profile_image', models.CharField(max_length=200, null=True)),
                ('Total_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('imagefield', models.CharField(max_length=200, null=True)),
                ('points', models.IntegerField()),
                ('nb_images', models.IntegerField()),
                ('nb_answers', models.IntegerField()),
                ('time', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, null=True)),
                ('definition', models.TextField(null=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Question')),
            ],
        ),
    ]
