# Generated by Django 3.0.3 on 2021-10-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('microscopy', models.CharField(max_length=200)),
                ('cell_type', models.CharField(max_length=200)),
                ('component', models.CharField(max_length=200)),
                ('organism', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('nb_images', models.IntegerField()),
                ('images', models.ManyToManyField(blank=True, related_name='question', to='learn.Images')),
            ],
        ),
        migrations.CreateModel(
            name='Answer_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Question')),
            ],
        ),
    ]
