# Generated by Django 3.0.3 on 2021-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='question', to='learn.Images'),
        ),
    ]
