# Generated by Django 3.0.3 on 2021-11-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_question_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Quiz',
        ),
    ]
