# Generated by Django 3.0.3 on 2021-11-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20211111_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stats',
            new_name='Stat',
        ),
        migrations.AlterField(
            model_name='stat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Profile'),
        ),
    ]
