# Generated by Django 3.0.3 on 2021-11-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20211121_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Profile'),
        ),
    ]
